docker push ghcr.io/theartofficial/artofficialstudio:latest
docker push ghcr.io/theartofficial/artofficialstudio:cu126latest
docker push ghcr.io/theartofficial/artofficialstudio:cu125latest
docker push ghcr.io/theartofficial/artofficialstudio:cu124latest
docker push theartofficial/artofficialstudio:latest
docker push theartofficial/artofficialstudio:cu126latest
docker push theartofficial/artofficialstudio:cu125latest
docker push theartofficial/artofficialstudio:cu124latest